#!/usr/bin/env bash
# Allows symlink or nonsymlink versions of script. eg. if calling from symlink file in ~/.bin
src="$(dirname "$( [ -L "$0" ] && readlink -f "$0" || echo "$0" )")" 
bqn $src/src/v.bqn $@
